name: to_do
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dartz: ^0.10.1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  path_provider: ^2.1.5
  flutter_riverpod: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
  assets:
    - assets/images/
flutter_assets:
  assets_path:
    - assets/images/
  output_path: lib/Core/utils
  filename: appimages.dart
  classname: AppImages
  ignore_comments: true
